flashcast: error check mount call

diff --git a/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image b/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image
--- a/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image
+++ b/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image
@@ -82,7 +82,10 @@ mount_mtd_partition() {
 
 	_MOUNT_DIR="$(mktemp -d)"
 	log "Mounting ${1} (${_PARTITION}) at ${_MOUNT_DIR}"
-	mount "/dev/mtdblock${_PARTITION#mtd}" "$_MOUNT_DIR"
+	if ! mount "/dev/mtdblock${_PARTITION#mtd}" "$_MOUNT_DIR" ; then
+		log "Could not mount MTD partition ${1}"
+		return 1;
+	fi
 	echo "$_MOUNT_DIR"
 }
 
