flashcast: don't write mtd partition when mksquashfs fails

diff --git a/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image b/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image
--- a/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image
+++ b/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image
@@ -167,7 +167,11 @@ end_squashfs_edit() {
 	log "Reflashing squashfs union at ${_WRAPPER}"
 
 	_REPACKED_FS="${_WRAPPER}/repack.sqfs"
-	mksquashfs "${_WRAPPER}/union" "$_REPACKED_FS" -no-progress
+	if ! mksquashfs "${_WRAPPER}/union" "$_REPACKED_FS" -no-progress ; then
+		log "Failed to repack squashfs image at ${_WRAPPER}"
+		return 1
+	fi
+
 	flash_mtd_partition "$(cat "${_WRAPPER}/mtdpart")" "${_WRAPPER}/repack.sqfs"
 
 	fusermount -u "${_WRAPPER}/union"
