flashcast: don't require imager.sh to be executable

diff --git a/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image b/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image
--- a/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image
+++ b/board/tchebb/eureka/fs-overlay_flasher/usr/sbin/flash-image
@@ -203,8 +203,8 @@ echo "Flashing mod at ${IMAGE_PATH}"
 trap "cd '$PWD'" EXIT 
 cd "$IMAGE_PATH"
 
-if ! test -x './imager.sh' ; then
-	echo "ERROR: $(pwd)/imager.sh does not exist or is not executable"
+if ! test -f './imager.sh' ; then
+	echo "ERROR: $(pwd)/imager.sh does not exist"
 	exit 1
 fi
 
